---
# tasks file for nf
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  when: "inventory_hostname == groups['manager'][0]"

- name: Ensure nfs is running.
  service:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: "yes"
  when: "inventory_hostname == groups['manager'][0]"

- name: reload nfs
  command: "exportfs -ra"
  when: "inventory_hostname == groups['manager'][0]"

- name: Mount NFS share
  become: true
  mount:
    fstype: nfs
    name: "/mnt/volume/"
    state: mounted
    src: "{{hostvars[groups['manager'][0]]['ansible_default_ipv4']['address']}}:/mnt/volume/"
  when: "inventory_hostname != groups['manager'][0]"
